### ISSUE TITLE
参考文献不能正常工作

### ISSUE THREAD

**Issue by cyPABLO123456cy** [Saltsmart/Latex-homowork#1]
当我编写完参考文献之后 编译之后 引文部分不能够正确显示

报错是 empty bibliography

如下图所示：
![img](https://gitee.com/pablocy/privatepicrepo/raw/master/img/20220603192634.png)

**Comment by Saltsmart** [comment]
这张图片失效了，请你重新发一下

另外也可检查这些方面：

1. 本模板是在TexLive2019版下创建的，在Overleaf上用了2021版，比较低的版本编译容易出问题；
2. 是否之前一次编译有其它错误，导致生成的中间文件不正确？这种情况下应当把所有编译产生的临时文件删掉，再次编译试一下（[参考链接](https://tex.stackexchange.com/questions/140701/empty-bibliography)）；
3. 是否按照xelatex->biblatex->xelatex->xelatex之类的顺序编译（[参考链接](https://ask.latexstudio.net/ask/article/93.html)）？注意一定不要用pdflatex，这个模板不支持它

**Comment by Saltsmart** [comment]
如果是使用overleaf的话，对照一下他们文档中的example，一般排错可以很好应对。[参考](https://www.overleaf.com/learn/latex/Bibliography_management_in_LaTeX)
